@extends:
    '@parent'

form:
  fields:
    widget_section:
      type: section
      title: PLUGIN_WIDGET.GLOBAL_WIDGET
      text: PLUGIN_WIDGET.GLOBAL_WIDGET_HELP
      underline: true

      fields:
        widget.areas:
          label: PLUGIN_WIDGET.WIDGET_AERAS
          type: list
          style: vertical
          btnLabel: PLUGIN_WIDGET.ADD_LOCATION

          import@:
            type: widget_areas
            context: blueprints://